name: DamageModifier
version: 1.1
main: code.damagemodifier.DamageModifier
api-version: '1.21'
commands:
  dm:
    description: DamageModifier parancsok
    usage: /dm reload
permissions:
  damagemodifier.reload:
    description: Lehetővé teszi a config újratöltését
    default: op
