name: DamageModifier
version: 1.1
main: code.damagemodifier.DamageModifier
api-version: '1.21'
commands:
  dm:
    description: DamageModifier reload command
    usage: /dm reload
permissions:
  damagemodifier.reload:
    description: Allows reloading the config
    default: op
