name: DamageModifier
version: 1.1
# Ennek pontosan egyeznie kell a Java kód "package" sorával + az osztály nevével
main: code.damagemodifier.DamageModifier
api-version: 1.21
commands:
  dm:
    description: Fő parancs
    usage: /dm reload
permissions:
  damagemodifier.reload:
    description: Lehetővé teszi a config újratöltését
    default: op
